<script>
window.validation_errors_language = {
	errorTitle: "<?php echo __('Form submission failed!') ?>",
	requiredFields: "<?php echo __('This field is required') ?>",
	badTime: "<?php echo __('You have not given a correct time') ?>",
	badEmail: "<?php echo __('You have not given a correct e-mail address') ?>",
	badTelephone: "<?php echo __('You have not given a correct phone number') ?>",
	badSecurityAnswer: "<?php echo __('You have not given a correct answer to the security question') ?>",
	badDate: "<?php echo __('You have not given a correct date') ?>",
	lengthBadStart: "<?php echo __('The input value must be between ') ?>",
	lengthBadEnd: "<?php echo __(' characters') ?>",
	lengthTooLongStart: "<?php echo __('The input value is longer than ') ?>",
	lengthTooShortStart: "<?php echo __('The input value is shorter than ') ?>",
	notConfirmed: "<?php echo __('Input values could not be confirmed') ?>",
	badDomain: "<?php echo __('Incorrect domain value') ?>",
	badUrl: "<?php echo __('The input value is not a correct URL') ?>",
	badCustomVal: "<?php echo __('The input value is incorrect') ?>",
	andSpaces: "<?php echo __(' and spaces ') ?>",
	badInt: "<?php echo __('The input value was not a correct number') ?>",
	badSecurityNumber: "<?php echo __('Your social security number was incorrect') ?>",
	badUKVatAnswer: "<?php echo __('Incorrect UK VAT Number') ?>",
	badStrength: "<?php echo __('The password isn\'t strong enough') ?>",
	badNumberOfSelectedOptionsStart: "<?php echo __('You have to choose at least ') ?>",
	badNumberOfSelectedOptionsEnd: "<?php echo __(' answers') ?>",
	badAlphaNumeric: "<?php echo __('The input value can only contain alphanumeric characters ') ?>",
	badAlphaNumericExtra: "<?php echo __(' and ') ?>",
	wrongFileSize: "<?php echo __('The file you are trying to upload is too large (max %s)') ?>",
	wrongFileType: "<?php echo __('Only files of type %s is allowed') ?>",
	groupCheckedRangeStart: "<?php echo __('Please choose between ') ?>",
	groupCheckedTooFewStart: "<?php echo __('Please choose at least ') ?>",
	groupCheckedTooManyStart: "<?php echo __('Please choose a maximum of ') ?>",
	groupCheckedEnd: "<?php echo __(' item(s)') ?>",
	badCreditCard: "<?php echo __('The credit card number is not correct') ?>",
	badCVV: "<?php echo __('The CVV number was not correct') ?>"
};
</script>