@DB_HOST = 'DB_HOST'
@DB_PORT = 'DB_PORT'
@DB_USER = 'DB_USER'
@DB_PASS = 'DB_PASS'
@DB_NAME = 'DB_NAME'

@GOOGLE_APP_NAME = 'necampus'
@GOOGLE_OAUTH_CLIENT_ID = ''
@GOOGLE_OAUTH_CLIENT_SECRET = ''
@GOOGLE_SITE_NAME = 'necampus'

@REDIS_HOST = ''
@REDIS_PORT = ''
@REDIS_PASS = ''
